# Generated by Django 5.0.6 on 2024-06-20 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exploiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='exploiter/')),
                ('background_image', models.ImageField(upload_to='background-exploiter/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_online', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='follower_image/')),
                ('background_image', models.ImageField(upload_to='background-follower-image/')),
                ('has_follower', models.BooleanField(default=False)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.exploiter')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
