# Generated by Django 5.0.6 on 2024-06-14 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategorya', 'verbose_name_plural': 'Kategoryalar'},
        ),
    ]
