# Generated by Django 5.0.6 on 2024-06-19 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_rename_name_cards_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
